# Generated by Django 4.2.3 on 2023-07-09 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_remove_ingredient_amount_recipeingridients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingridients',
            name='amount',
            field=models.IntegerField(default=1, verbose_name=django.core.validators.MinValueValidator(1)),
            preserve_default=False,
        ),
    ]
