# Generated by Django 4.2.3 on 2023-07-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_rename_recipeingridients_recipeingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
