# Generated by Django 4.2.3 on 2023-07-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0006_rename_ingredient_recipeingredients_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredientsModel',
        ),
    ]
