# Generated by Django 4.2.3 on 2023-07-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0007_rename_recipeingredients_recipeingredientsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredientsModel',
            new_name='RecipeIngredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
