# Generated by Django 4.2.3 on 2023-07-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0012_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
