# Generated by Django 4.2.3 on 2023-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0014_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recepies/', verbose_name='Картинка'),
        ),
    ]
